---
title: "Shiny your Research"
subtitle: "Building Interactive Dashboards in R"
date: "July 10, 2026"
format: 
  revealjs:
    theme: night
    transition: slide
    highlight-style: github
    slide-number: c/t
    chalkboard: true
    footer: ""
---


# 1. Introductions 

-  Shiny Your Research

-  Interactive Dashboards in R for Dementia Research

**AAIC 2026 ISTAART Immersives**

**Attendance at this conference was supported by an AAIC 2026 Conference Fellowship.**


------------------------------------------------------------------------

## 1.1 Welcome {.smaller}

-   **Rory Chen, MSc** 
-   **Ana W. Capuano, PhD** 
-   **Sarah Bauermeister, PhD** 
-   **Graham Bearden, PhD** 
-   **Ashleigh Vella, PhD** 
-   **James Lian, PhD** 

------------------------------------------------------------------------

## 1.2 Today's agenda {.smaller}

The workshop will run for 4 hours, 1-5 pm.

-   1:00 - 1:30 p.m. - Introductions and Scene Setting

-   1:30 - 2:00 p.m. - Theory and Real-World App Demo

-   2:00 - 3:00 p.m. - Guided Practice: Build Your First Shiny App

-   3:00 - 3:30 p.m. - Break

-   3:30 - 4:30 p.m. - Independent Hands-On Exercise

-   4:30 - 5:00 p.m. - Group Sharing and Wrap-Up

------------------------------------------------------------------------

## 1.3 Why use `shiny` for your research {.smaller}

- `Interactive`: Turn static figures and tables into explorable dashboards and web apps.

- `R-native`: Build applications directly from R without needing extensive HTML, CSS, or JavaScript knowledge.

- `Accessible`: Share research tools through a web browser using a simple URL.

- `Engaging`: Support presentations, teaching, collaboration, and data exploration through interactive visualisations.

- `Customisable`: Adapt apps for different datasets, audiences, and research questions.

... and more!

------------------------------------------------------------------------

## 1.4 Learning Objectives {.smaller}

By the end of this workshop, you will be able to:

- Understand the core concepts and features behind `shiny` applications.

- Create an interactive `shiny` dashboard through guided hands-on coding.

- Design reproducible and scalable `shiny` workflows using structured development practices.

- Independently apply `shiny` to present own scientific outputs in an engaging, accessible format.

- Explore integration of large language models (LLMs) using the `ellmer` and `querychat` packages.

------------------------------------------------------------------------

## 1.5 Setup

-   You are comfortable coding in R and R Studio
-   No prior knowledge of Shiny apps required.
-   Access Github:
-   Access your Anthropic key and and save it to .Renviron
-   Install the required package if you haven't already
-   If you have any troubles, please raise your hand, one of the facilitators will come to assist you.

```{r}
#| echo: true
#| eval: false
install.packages(c("ellmer", "shinychat", "shiny", "bslib"))
```
